Changes for select mode operation
nisargjhaveri/WirelessAndroidAutoDongle pull request #56
Opened 2024-02-17 20:38 UTC by Ioniq3

The behaviour first phone or usb may change depends on car headunit. 

The file /root/.env can use for this. It cannot be put in the /boot of the first partition of the sd because buildroot doesn't mount it by default.

2024-02-20 16:41 UTC, Ioniq3 commented on aa_wireless_dongle/package/aawg/src/aawgd.cpp
> +        if (const char* env_p = std::getenv("HEADUNIT_FIRST")) {
nothing, get the actual behavior of the main

2024-02-20 19:21 UTC, nisargjhaveri requested changes

2024-02-20 19:21 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/init.d/S93aawgd
> +		export $(grep -v '^#' /root/.env | xargs)
Instead of parsing a .env file like this, let's just have a shell script that exports variables and simply source it here?

2024-02-20 19:21 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/root/.env
> +#HEADUNIT_FIRST=1
Since this will be an env variable, let's make it some more specific and consistent with other env variables we support. `AAWG_CONNECTION_WAIT_FOR_ACCESSORY` or similar seems more appropriate to me.

2024-02-20 19:21 UTC, nisargjhaveri commented on aa_wireless_dongle/package/aawg/src/aawgd.cpp
> +        UsbManager::instance().enableDefaultAndWaitForAccessroy();
Please indent this?

2024-02-20 19:21 UTC, nisargjhaveri commented on aa_wireless_dongle/package/aawg/src/proxyHandler.cpp
> +            Logger::instance()->info("Head Unit first connection selected\n");
Let's log at the beginning of the connection in aawgd.cpp. Something like "Waiting for the accessory to connect first" in case the variable is set. We don't need additional logging here as such.

2024-02-20 19:21 UTC, nisargjhaveri commented on aa_wireless_dongle/package/aawg/src/proxyHandler.cpp
> +        }
Indentation seems off in these changes, could you please fix? Sorry for nitpicking.

2024-02-21 19:20 UTC, Ioniq3 commented on aa_wireless_dongle/package/aawg/src/proxyHandler.cpp
> +            Logger::instance()->info("Head Unit first connection selected\n");
ok, do it

2024-02-21 19:20 UTC, Ioniq3 commented on aa_wireless_dongle/package/aawg/src/proxyHandler.cpp
> +        }
ok

2024-02-21 19:20 UTC, Ioniq3 commented on aa_wireless_dongle/board/common/rootfs_overlay/root/.env
> +#HEADUNIT_FIRST=1
ok

2024-02-21 19:22 UTC, Ioniq3 commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/init.d/S93aawgd
> +		export $(grep -v '^#' /root/.env | xargs)
I did what the expert said whas the best solution based on https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs
in some case the exportation doesn't work but this way I tested that work.
If someone send me another tested way I'll change

2024-02-23 17:35 UTC, Ioniq3 commented on aa_wireless_dongle/package/aawg/src/aawgd.cpp
> +        UsbManager::instance().enableDefaultAndWaitForAccessroy();
ok

2024-02-23 19:14 UTC, nisargjhaveri requested changes

2024-02-23 19:14 UTC, nisargjhaveri commented on aa_wireless_dongle/package/aawg/src/proxyHandler.cpp
> +    } else {
We should be able to change this to a not condition and avoid the empty if block

```
if (!(const char* env_p = std::getenv("AAWG_CONNECTION_WAIT_FOR_ACCESSORY"))) {
```

2024-02-23 19:14 UTC, nisargjhaveri commented on aa_wireless_dongle/package/aawg/src/aawgd.cpp
> +            Logger::instance()->info("Waiting for the accessory to connect first\n");
The log needs to go before the wait call. Otherwise this will be logged after we already have connected to the USB.

2024-02-23 19:14 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/root/.env
> +#AAWG_CONNECTION_WAIT_FOR_ACCESSORY=1
Can we move the documentation around this here only instead of README?

2024-02-23 19:14 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/init.d/S93aawgd
> +		export $(grep -v '^#' /root/.env | xargs)
I was actually suggesting writing a full sh file similar to this answer: https://stackoverflow.com/a/19331521

But this works too.

2024-02-23 19:14 UTC, nisargjhaveri commented on README.md
> +### Enviroment variables
Let's remove this from readme for now? We can add once we stabilise this for a while.

2024-02-23 19:14 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/init.d/S93aawgd
> +		export $(grep -v '^#' /root/.env | xargs)
Instead of `/root/.env`, how about `/etc/aawgd.env`?

2024-02-24 17:16 UTC, Ioniq3 commented on aa_wireless_dongle/package/aawg/src/proxyHandler.cpp
> +    } else {
ok, done

2024-02-24 17:19 UTC, Ioniq3 commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/init.d/S93aawgd
> +		export $(grep -v '^#' /root/.env | xargs)
ok, i put it there because it is the default folder when if you ssh into, but it really doesn't matter.

2024-02-24 17:22 UTC, Ioniq3 commented on README.md
> +### Enviroment variables
ok, done

2024-02-24 17:22 UTC, Ioniq3 commented on aa_wireless_dongle/board/common/rootfs_overlay/root/.env
> +#AAWG_CONNECTION_WAIT_FOR_ACCESSORY=1
ok, done

2024-02-25 17:02 UTC, nisargjhaveri approved these changes
I made some very small changes. Waiting for the build to succeed. Thanks a lot for spending time on this! :)

2024-02-29 04:10 UTC, merged

2024-02-29 04:10 UTC, nisargjhaveri commented
Thanks a lot @Ioniq3 for the PR!